/* Usage: bin2ov5640fw < fw.bin > ov5640_af_firmware.h */

#include <stdio.h>
#include <unistd.h>

int main()
{
	unsigned char buf[0x1000];
	int i, len;

	len = read(0, buf, sizeof(buf));
	if (len < 0) {
		fprintf(stderr, "read stdin: %m\n");
		return 1;
	}

	printf("/* Generated by bin2ov5640fw */\n\n");

	printf("static struct reg_value ov5640_af_firmware[] = {");
	for (i = 0; i < len; i++) {
		printf("%s{0x%04x, 0x%02x, 0, 0}%s",
				((i % 3) == 0) ? "\n\t" : " ",
				i + 0x8000,
				buf[i],
				(i < len - 1) ? "," : "");
	}
	printf("\n};\n");

	return 0;
}
